import 'package:equatable/equatable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'dart:async';
import 'package:mnjz_task/src/core/usecases/usecase.dart';
import 'package:mnjz_task/src/features/products/domain/domain.dart';
import '../../../../core/error/error_cases.dart';
part 'event.dart';
part 'state.dart';
part 'products.dart';
